services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s

  app:
    image: coupon-service:latest
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_FLYWAY_URL: jdbc:${DATABASE_URL}
      SPRING_R2DBC_URL: r2dbc:${DATABASE_URL}
      SPRING_R2DBC_USERNAME: ${DATABASE_USERNAME}
      SPRING_R2DBC_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s

  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DATABASE_NAME} -U ${DATABASE_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: