# nginx.conf
events {}
http {
  upstream app {
    server app:8080;   # Docker rozwiązuje wszystkie repliki po nazwie serwisu
  }
  server {
    listen 80;
    location / { proxy_pass http://app; }
  }
}